dt: 0.1
dv: 0.01
dyaw: 0.01
max_speed: 0.42
min_speed: 0.0
max_accel: 5.0
max_yawrate: 1.00
max_dyawrate: 2.0
robot_radius: 0.17

predict_time: 5.0
l_ob_cost_gain: 1.0
to_g_goal_cost_gain: 1.0

limit_speed: 0.1
limit_yawrate: 0.25

dwa_only: false
