dt: 0.1
dv: 0.01
dyaw: 0.01
max_speed: 0.42
min_speed: 0.0
max_accel: 5.0
max_yawrate: 1.00
max_dyawrate: 2.0
roomba_radius: 0.16

predict_time: 5.0
l_ob_cost_gain: 0.20
to_g_goal_cost_gain: 0.80

limit_speed: 0.07
limit_yawrate: 0.25

dwa_only: false

stop_time: 5.0
ignore_line: 1.0
