dt: 0.1
dv: 0.01
dyaw: 0.01
max_speed: 0.40
min_speed: 0.0
max_accel: 2.0
max_yawrate: 0.87
min_yawrate: -0.87
max_dyawrate: 2.0
robot_radius: 0.17
limit_speed: 0.20
limit_yawrate: 0.20

predict_time: 3.0
l_ob_cost_gain: 1.0
speed_cost_gain: 1.0
omega_cost_gain: 0.0
to_g_goal_cost_gain: 0.0
dis_g_goal_cost_gain: 0.0
to_g_path_cost_gain: 0.0
dis_g_path_cost_gain: 0.0
